[metadata]
name = legacy-tool
version = attr: legacy_tool.__version__

[options]
python_requires = >=3.8
install_requires =
    httpx[http2]==0.27.2
    tomli>=2.0 ; python_version < "3.11"
setup_requires =
    wheel==0.44.0
tests_require =
    hypothesis==6.112.0

[options.extras_require]
docs =
    sphinx==8.0.2
