"""Minimal real-format projects, one builder per ecosystem, for the checks every ecosystem gets.

A builder writes the files an ecosystem's tooling would -- a manifest and, where the ecosystem has
one, a lockfile -- for a list of packages, so one universal test (`test_universal.py`) can ask the
same question of every ecosystem: is an affected version found and an unaffected one not, is a
known-malicious release named, is a tampered hash reported, does a large lockfile stay bounded.

The formats are the ones the real-world cases under `cases/` were generated by the tools
themselves in; these builders write the smallest valid instance of each.
"""

from __future__ import annotations

import json
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class Pkg:
    name: str
    version: str
    integrity: str | None = None
    source: str | None = None
    """Where it resolves from, when not the default registry (a private registry URL)."""
    license: str | None = None
    """The licence the lockfile records, where the format records one."""


@dataclass(frozen=True)
class EcosystemProfile:
    """What the universal tests need to know about one ecosystem."""

    id: str
    names: tuple[str, str, str]
    """Three ordinary, distinct package names valid in the ecosystem."""
    versions: tuple[str, str, str]
    """An affected version, the first fixed version, and a later one -- in the ecosystem's form."""
    write: Callable[[Path, list[Pkg]], None]
    hash_of: Callable[[int], str] | None = None
    """A well-formed digest for entry n, where the format records one."""
    malformed_hash: str | None = None
    typosquat: tuple[str, str, str] | None = None
    """(a popular package, a one-edit slip of it, a legitimate look-alike that is real)."""
    internal: tuple[str, str] | None = None
    """(an internal namespace prefix, a package name under it)."""
    private_source: str | None = None
    """A resolved-from value that is a private registry, for the confusion test."""
    executable: dict[str, str] = field(default_factory=dict)
    """Files of the ecosystem's that are code: if parsing ran them, `MARKER` would exist."""
    records_licence: bool = False
    """The format records each package's licence (npm's lockfile does), so allow and deny lists
    can be judged offline."""
    registry_digests: bool = True
    """The registry publishes the digest the lockfile records, so the online comparison can be
    exercised. CRAN publishes none for renv's record; its registry is proven by unit tests."""


MARKER = "/tmp/cordon-conformance-executed"


class Writers:
    @staticmethod
    def npm(root: Path, pkgs: list[Pkg]) -> None:
        deps = {p.name: p.version for p in pkgs}
        (root / "package.json").write_text(
            json.dumps({"name": "app", "version": "1.0.0", "dependencies": deps}), encoding="utf-8"
        )
        packages: dict[str, object] = {
            "": {"name": "app", "version": "1.0.0", "dependencies": deps}
        }
        for p in pkgs:
            entry: dict[str, object] = {
                "version": p.version,
                "resolved": p.source
                or f"https://registry.npmjs.org/{p.name}/-/{p.name.rpartition('/')[2]}-{p.version}.tgz",
            }
            if p.integrity:
                entry["integrity"] = p.integrity
            if p.license:
                entry["license"] = p.license
            packages[f"node_modules/{p.name}"] = entry
        (root / "package-lock.json").write_text(
            json.dumps(
                {
                    "name": "app",
                    "version": "1.0.0",
                    "lockfileVersion": 3,
                    "requires": True,
                    "packages": packages,
                }
            ),
            encoding="utf-8",
        )

    @staticmethod
    def pypi(root: Path, pkgs: list[Pkg]) -> None:
        lines = []
        for p in pkgs:
            line = f"{p.name}=={p.version}"
            if p.integrity:
                line += f" \\\n    --hash={p.integrity}"
            lines.append(line)
        index = next((p.source for p in pkgs if p.source), None)
        head = f"--index-url {index}\n" if index else ""
        (root / "requirements.txt").write_text(head + "\n".join(lines) + "\n", encoding="utf-8")

    @staticmethod
    def cargo(root: Path, pkgs: list[Pkg]) -> None:
        manifest = (
            '[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n'
        )
        manifest += "".join(f'{p.name} = "={p.version}"\n' for p in pkgs)
        (root / "Cargo.toml").write_text(manifest, encoding="utf-8")
        lock = 'version = 3\n\n[[package]]\nname = "app"\nversion = "0.1.0"\ndependencies = [\n'
        lock += "".join(f' "{p.name}",\n' for p in pkgs) + "]\n"
        for p in pkgs:
            source = p.source or "registry+https://github.com/rust-lang/crates.io-index"
            lock += (
                f'\n[[package]]\nname = "{p.name}"\nversion = "{p.version}"\nsource = "{source}"\n'
            )
            if p.integrity:
                lock += f'checksum = "{p.integrity}"\n'
        (root / "Cargo.lock").write_text(lock, encoding="utf-8")

    @staticmethod
    def gomod(root: Path, pkgs: list[Pkg]) -> None:
        mod = (
            "module example.com/app\n\ngo 1.22\n\nrequire (\n"
            + "".join(f"\t{p.name} {p.version}\n" for p in pkgs)
            + ")\n"
        )
        (root / "go.mod").write_text(mod, encoding="utf-8")
        (root / "go.sum").write_text(
            "".join(f"{p.name} {p.version} {p.integrity}\n" for p in pkgs if p.integrity),
            encoding="utf-8",
        )

    @staticmethod
    def maven(root: Path, pkgs: list[Pkg]) -> None:
        """A POM, Maven's `dependency:tree` output beside it, and -- where hashes are given --
        Maven Resolver's trusted checksums in `.mvn/checksums/`, in the layouts the real-world
        cases (`cases/maven/`) were generated in."""
        dependencies = "".join(
            f"    <dependency><groupId>{p.name.partition(':')[0]}</groupId>"
            f"<artifactId>{p.name.partition(':')[2]}</artifactId><version>{p.version}</version></dependency>\n"
            for p in pkgs
        )
        (root / "pom.xml").write_text(
            '<?xml version="1.0" encoding="UTF-8"?>\n<project xmlns="http://maven.apache.org/POM/4.0.0">\n'
            "  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.example</groupId>\n  <artifactId>app</artifactId>\n"
            f"  <version>1.0.0</version>\n  <dependencies>\n{dependencies}  </dependencies>\n</project>\n",
            encoding="utf-8",
        )
        tree = ["com.example:app:jar:1.0.0"]
        for index, p in enumerate(pkgs):
            branch = "\\- " if index == len(pkgs) - 1 else "+- "
            tree.append(f"{branch}{p.name}:jar:{p.version}:compile")
        (root / "dependency-tree.txt").write_text("\n".join(tree) + "\n", encoding="utf-8")
        hashed = [p for p in pkgs if p.integrity]
        if hashed:
            (root / ".mvn" / "checksums").mkdir(parents=True, exist_ok=True)
            lines = []
            for p in hashed:
                group, _, artifact = p.name.partition(":")
                lines.append(
                    f"{p.integrity}  {group.replace('.', '/')}/{artifact}/{p.version}/{artifact}-{p.version}.jar"
                )
            (root / ".mvn" / "checksums" / "checksums-central.sha256").write_text(
                "\n".join(lines) + "\n", encoding="utf-8"
            )

    @staticmethod
    def gradle(root: Path, pkgs: list[Pkg]) -> None:
        """A Kotlin build script, Gradle's `gradle.lockfile` and -- where hashes are given -- its
        `gradle/verification-metadata.xml`, as in `cases/gradle/real-multiproject`."""
        body = "".join(f'    implementation("{p.name}:{p.version}")\n' for p in pkgs)
        (root / "build.gradle.kts").write_text(
            "plugins {\n    `java-library`\n}\n\ndependencyLocking {\n    lockAllConfigurations()\n}\n\n"
            f"dependencies {{\n{body}}}\n",
            encoding="utf-8",
        )
        lock = "# This is a Gradle generated file for dependency locking.\n"
        lock += "".join(f"{p.name}:{p.version}=compileClasspath,runtimeClasspath\n" for p in pkgs)
        (root / "gradle.lockfile").write_text(
            lock + "empty=annotationProcessor\n", encoding="utf-8"
        )
        hashed = [p for p in pkgs if p.integrity]
        if hashed:
            (root / "gradle").mkdir(exist_ok=True)
            components = "".join(
                f'      <component group="{p.name.partition(":")[0]}" name="{p.name.partition(":")[2]}" version="{p.version}">\n'
                f'         <artifact name="{p.name.partition(":")[2]}-{p.version}.jar">\n'
                f'            <sha256 value="{p.integrity}" origin="Generated by Gradle"/>\n'
                "         </artifact>\n      </component>\n"
                for p in hashed
            )
            (root / "gradle" / "verification-metadata.xml").write_text(
                '<?xml version="1.0" encoding="UTF-8"?>\n'
                '<verification-metadata xmlns="https://schema.gradle.org/dependency-verification">\n'
                f"   <components>\n{components}   </components>\n</verification-metadata>\n",
                encoding="utf-8",
            )

    @staticmethod
    def nuget(root: Path, pkgs: list[Pkg]) -> None:
        """A project file and NuGet's `packages.lock.json`, as in
        `cases/nuget/real-central-management`."""
        references = "".join(
            f'    <PackageReference Include="{p.name}" Version="{p.version}" />\n' for p in pkgs
        )
        (root / "App.csproj").write_text(
            '<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup>\n    <TargetFramework>net8.0</TargetFramework>\n'
            "    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>\n  </PropertyGroup>\n"
            f"  <ItemGroup>\n{references}  </ItemGroup>\n</Project>\n",
            encoding="utf-8",
        )
        entries: dict[str, object] = {}
        for p in pkgs:
            entry: dict[str, object] = {
                "type": "Direct",
                "requested": f"[{p.version}, )",
                "resolved": p.version,
            }
            if p.integrity:
                entry["contentHash"] = p.integrity
            entries[p.name] = entry
        (root / "packages.lock.json").write_text(
            json.dumps({"version": 1, "dependencies": {"net8.0": entries}}, indent=2),
            encoding="utf-8",
        )

    @staticmethod
    def composer(root: Path, pkgs: list[Pkg]) -> None:
        """composer.json and composer.lock, as in `cases/composer/real-application`: packages from
        Packagist carry its `notification-url`, and a private repository's `shasum` is recorded."""
        require = {p.name: p.version for p in pkgs}
        (root / "composer.json").write_text(
            json.dumps({"name": "acme/app", "require": require}, indent=4), encoding="utf-8"
        )
        packages = []
        for p in pkgs:
            entry: dict[str, object] = {
                "name": p.name,
                "version": p.version,
                "dist": {
                    "type": "zip",
                    "url": p.source or f"https://api.github.com/repos/{p.name}/zipball/{'0' * 40}",
                    "reference": "0" * 40,
                    "shasum": p.integrity or "",
                },
                "type": "library",
            }
            if not p.source:
                entry["notification-url"] = "https://packagist.org/downloads/"
            if p.license:
                entry["license"] = [p.license]
            packages.append(entry)
        (root / "composer.lock").write_text(
            json.dumps(
                {"content-hash": "0" * 32, "packages": packages, "packages-dev": [], "aliases": []},
                indent=4,
            ),
            encoding="utf-8",
        )

    @staticmethod
    def rubygems(root: Path, pkgs: list[Pkg]) -> None:
        """A Gemfile and Bundler's Gemfile.lock with a CHECKSUMS section, as in
        `cases/rubygems/real-bundler`."""
        (root / "Gemfile").write_text(
            'source "https://rubygems.org"\n\n'
            + "".join(f'gem "{p.name}", "{p.version}"\n' for p in pkgs),
            encoding="utf-8",
        )
        private = next((p.source for p in pkgs if p.source), None)
        lock = ["GEM", f"  remote: {private or 'https://rubygems.org/'}", "  specs:"]
        lock += [f"    {p.name} ({p.version})" for p in sorted(pkgs, key=lambda p: p.name)]
        lock += ["", "PLATFORMS", "  ruby", "", "DEPENDENCIES"]
        lock += [f"  {p.name} (= {p.version})" for p in sorted(pkgs, key=lambda p: p.name)]
        if any(p.integrity for p in pkgs):
            lock += ["", "CHECKSUMS"]
            lock += [
                f"  {p.name} ({p.version})" + (f" sha256={p.integrity}" if p.integrity else "")
                for p in sorted(pkgs, key=lambda p: p.name)
            ]
        lock += ["", "BUNDLED WITH", "   2.6.2", ""]
        (root / "Gemfile.lock").write_text("\n".join(lock), encoding="utf-8")

    @staticmethod
    def hex(root: Path, pkgs: list[Pkg]) -> None:
        """mix.exs and mix.lock, as in `cases/hex/real-umbrella`. A package from a private Hex
        repository records that repository's name."""
        deps = ",\n      ".join(f'{{:{p.name}, "{p.version}"}}' for p in pkgs)
        (root / "mix.exs").write_text(
            "defmodule App.MixProject do\n  use Mix.Project\n\n  def project do\n"
            '    [app: :app, version: "0.1.0", deps: deps()]\n  end\n\n'
            f"  defp deps do\n    [\n      {deps}\n    ]\n  end\nend\n",
            encoding="utf-8",
        )
        lines = []
        for p in sorted(pkgs, key=lambda p: p.name):
            repository = "acme" if p.source else "hexpm"
            outer = p.integrity or ""
            lines.append(
                f'  "{p.name}": {{:hex, :{p.name}, "{p.version}", "{"0" * 64}", [:mix], [], "{repository}", "{outer}"}},'
            )
        (root / "mix.lock").write_text("%{\n" + "\n".join(lines) + "\n}\n", encoding="utf-8")

    @staticmethod
    def pub(root: Path, pkgs: list[Pkg]) -> None:
        """pubspec.yaml and pubspec.lock, as in `cases/pub/real-workspace`."""
        (root / "pubspec.yaml").write_text(
            "name: app\npublish_to: none\nenvironment:\n  sdk: ^3.6.0\ndependencies:\n"
            + "".join(f'  "{p.name}": "{p.version}"\n' for p in pkgs),
            encoding="utf-8",
        )
        lines = ["packages:"]
        for p in sorted(pkgs, key=lambda p: p.name):
            lines += [
                f'  "{p.name}":',
                '    dependency: "direct main"',
                "    description:",
                f'      name: "{p.name}"',
            ]
            if p.integrity:
                lines.append(f'      sha256: "{p.integrity}"')
            lines += [
                f'      url: "{p.source or "https://pub.dev"}"',
                "    source: hosted",
                f'    version: "{p.version}"',
            ]
        lines += ["sdks:", '  dart: ">=3.6.0 <4.0.0"', ""]
        (root / "pubspec.lock").write_text("\n".join(lines), encoding="utf-8")

    @staticmethod
    def swift(root: Path, pkgs: list[Pkg]) -> None:
        """Package.swift and a version 2 Package.resolved, as in `cases/swift/real-package`."""
        dependencies = "".join(
            f'        .package(url: "https://github.com/{p.name}.git", exact: "{p.version}"),\n'
            for p in pkgs
        )
        (root / "Package.swift").write_text(
            "// swift-tools-version:5.9\nimport PackageDescription\n\nlet package = Package(\n"
            f'    name: "App",\n    dependencies: [\n{dependencies}    ],\n    targets: [.target(name: "App")]\n)\n',
            encoding="utf-8",
        )
        pins = [
            {
                "identity": p.name.rpartition("/")[2].lower(),
                "kind": "remoteSourceControl",
                "location": f"https://github.com/{p.name}.git",
                "state": {"revision": "0" * 40, "version": p.version},
            }
            for p in pkgs
        ]
        (root / "Package.resolved").write_text(
            json.dumps({"pins": pins, "version": 2}, indent=2), encoding="utf-8"
        )

    @staticmethod
    def cocoapods(root: Path, pkgs: list[Pkg]) -> None:
        """A Podfile and its Podfile.lock, as in `cases/cocoapods/real-podfile`."""
        (root / "Podfile").write_text(
            'platform :ios, "15.0"\n\ntarget "App" do\n'
            + "".join(f'  pod "{p.name}", "{p.version}"\n' for p in pkgs)
            + "end\n",
            encoding="utf-8",
        )
        private = [p for p in pkgs if p.source]
        lock = ["PODS:"] + [f"  - {p.name} ({p.version})" for p in pkgs]
        lock += ["", "DEPENDENCIES:"] + [f"  - {p.name} (= {p.version})" for p in pkgs]
        lock += ["", "SPEC REPOS:"]
        if private:
            lock += [f"  {private[0].source}:"] + [f"    - {p.name}" for p in private]
        public = [p for p in pkgs if not p.source]
        if public:
            lock += ["  trunk:"] + [f"    - {p.name}" for p in public]
        hashed = [p for p in pkgs if p.integrity]
        if hashed:
            lock += ["", "SPEC CHECKSUMS:"] + [f"  {p.name}: {p.integrity}" for p in hashed]
        lock += ["", "COCOAPODS: 1.17.0", ""]
        (root / "Podfile.lock").write_text("\n".join(lock), encoding="utf-8")

    @staticmethod
    def conda(root: Path, pkgs: list[Pkg]) -> None:
        """environment.yml and conda-lock.yml, as in `cases/conda/real-environment`."""
        (root / "environment.yml").write_text(
            "name: app\nchannels:\n  - conda-forge\ndependencies:\n"
            + "".join(f"  - {p.name}=={p.version}\n" for p in pkgs),
            encoding="utf-8",
        )
        lines = ["version: 1", "metadata:", "  platforms:", "  - linux-64", "package:"]
        for p in pkgs:
            base = p.source or "https://conda.anaconda.org/conda-forge"
            lines += [
                f"- name: {p.name}",
                f"  version: '{p.version}'",
                "  manager: conda",
                "  platform: linux-64",
                "  dependencies: {}",
                f"  url: {base}/linux-64/{p.name}-{p.version}-h0_0.conda",
            ]
            if p.integrity:
                lines += ["  hash:", f"    sha256: {p.integrity}"]
            lines += ["  category: main", "  optional: false"]
        (root / "conda-lock.yml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    @staticmethod
    def cran(root: Path, pkgs: list[Pkg]) -> None:
        """DESCRIPTION and an renv.lock in the renv < 1.1 layout (Requirements and Hash)."""
        imports = ",\n    ".join(f"{p.name} (== {p.version})" for p in pkgs)
        (root / "DESCRIPTION").write_text(
            f"Package: app\nVersion: 0.1.0\nLicense: MIT\nImports:\n    {imports}\n",
            encoding="utf-8",
        )
        packages = {}
        for p in pkgs:
            entry: dict[str, object] = {
                "Package": p.name,
                "Version": p.version,
                "Source": "Repository",
                "Repository": "CRAN",
                "Requirements": [],
            }
            if p.source:
                entry = {**entry, "Source": "URL", "RemoteUrl": p.source}
            if p.integrity:
                entry["Hash"] = p.integrity
            packages[p.name] = entry
        (root / "renv.lock").write_text(
            json.dumps({"R": {"Version": "4.4.3"}, "Packages": packages}, indent=2),
            encoding="utf-8",
        )

    @staticmethod
    def hackage(root: Path, pkgs: list[Pkg]) -> None:
        """A Stack project: an hpack package.yaml, stack.yaml with each package as an extra-dep,
        and the stack.yaml.lock Stack completes them into (a cabal-file hash per Hackage package,
        an archive URL for one from elsewhere)."""
        deps = "".join(f"  - {p.name} == {p.version}\n" for p in pkgs)
        (root / "package.yaml").write_text(
            f"name: app\nversion: 0.1.0\ndependencies:\n{deps}library:\n  source-dirs: src\n",
            encoding="utf-8",
        )
        extra = "".join(f"  - {p.name}-{p.version}\n" for p in pkgs)
        (root / "stack.yaml").write_text(
            f"snapshot: lts-22.33\npackages:\n  - .\nextra-deps:\n{extra}", encoding="utf-8"
        )
        lines = ["packages:"]
        for p in pkgs:
            if p.source:
                lines += [
                    "- completed:",
                    f"    url: {p.source}",
                    f"    name: {p.name}",
                    f"    version: {p.version}",
                    *([f"    sha256: {p.integrity}"] if p.integrity else []),
                    "  original:",
                    f"    url: {p.source}",
                ]
            else:
                pin = f"@sha256:{p.integrity},1024" if p.integrity else ""
                lines += [
                    "- completed:",
                    f"    hackage: {p.name}-{p.version}{pin}",
                    "  original:",
                    f"    hackage: {p.name}-{p.version}",
                ]
        lines += [
            "snapshots:",
            "- completed:",
            "    sha256: 098936027eaa1ef14e2b8eb39d9933a973894bb70a68684a1bbf00730249879b",
            "    size: 720001",
            "    url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/33.yaml",
            "  original: lts-22.33",
        ]
        (root / "stack.yaml.lock").write_text("\n".join(lines) + "\n", encoding="utf-8")

    @staticmethod
    def julia(root: Path, pkgs: list[Pkg]) -> None:
        """Project.toml and a format-2 Manifest.toml: each package a registry package with a UUID
        derived from its name, pinned by git-tree-sha1, or from a git URL when it has a source."""
        import uuid

        def ident(name: str) -> str:
            return str(uuid.uuid5(uuid.NAMESPACE_URL, f"conformance/{name}"))

        deps = "".join(f'{json.dumps(p.name)} = "{ident(p.name)}"\n' for p in pkgs)
        (root / "Project.toml").write_text(
            f'name = "App"\nuuid = "{ident("App")}"\n\n[deps]\n{deps}', encoding="utf-8"
        )
        lines = ['julia_version = "1.11.9"', 'manifest_format = "2.0"', ""]
        for p in pkgs:
            lines.append(f"[[deps.{json.dumps(p.name)}]]")
            if p.integrity:
                lines.append(f'git-tree-sha1 = "{p.integrity.removeprefix("git-tree-sha1:")}"')
            if p.source:
                lines.append(f'repo-url = "{p.source}"')
            lines += [f'uuid = "{ident(p.name)}"', f"version = {json.dumps(p.version)}", ""]
        (root / "Manifest.toml").write_text("\n".join(lines), encoding="utf-8")

    @staticmethod
    def opam(root: Path, pkgs: list[Pkg]) -> None:
        """A dune project and the dune.lock/ `dune pkg lock` writes: one .pkg per package, its
        archive's checksum in the `sha512=<hex>` form, a pin (`(dev)`) for a package with a source."""
        depends = "".join(f"\n  ({p.name} (= {p.version}))" for p in pkgs)
        (root / "dune-project").write_text(
            f"(lang dune 3.17)\n(package\n (name app)\n (depends{depends}))\n", encoding="utf-8"
        )
        lock = root / "dune.lock"
        lock.mkdir()
        (lock / "lock.dune").write_text("(lang package 0.1)\n", encoding="utf-8")
        for p in pkgs:
            fetch = f"(url {p.source or f'https://example.org/{p.name[:60]}-{p.version[:30]}.tbz'})"
            if p.integrity:
                fetch += f"\n  (checksum {p.integrity.replace(':', '=', 1)})"
            body = (
                f"(version {p.version})\n"
                + ("\n(dev)\n" if p.source else "")
                + f"\n(source\n (fetch\n  {fetch}))\n"
            )
            # A file name holds at most 255 bytes; the version inside the file is what is read.
            (lock / f"{p.name[:120]}.{p.version[:60]}.pkg").write_text(body, encoding="utf-8")

    @staticmethod
    def conan(root: Path, pkgs: list[Pkg]) -> None:
        """conanfile.txt and the Conan 2 lock: each reference with its recipe revision, and a
        user/channel for a package from a private remote."""
        (root / "conanfile.txt").write_text(
            "[requires]\n" + "".join(f"{p.name}/{p.version}\n" for p in pkgs), encoding="utf-8"
        )
        requires = []
        for p in pkgs:
            namespace = f"@{p.source}" if p.source else ""
            revision = f"#{p.integrity.removeprefix('md5:')}%1700000000.0" if p.integrity else ""
            requires.append(f"{p.name}/{p.version}{namespace}{revision}")
        (root / "conan.lock").write_text(
            json.dumps(
                {
                    "version": "0.5",
                    "requires": requires,
                    "build_requires": [],
                    "python_requires": [],
                    "config_requires": [],
                },
                indent=4,
            ),
            encoding="utf-8",
        )

    @staticmethod
    def vcpkg(root: Path, pkgs: list[Pkg]) -> None:
        """vcpkg.json in manifest mode, each port pinned by an override; a port with a source is
        served by an internal git registry the configuration routes its name to."""
        manifest: dict[str, object] = {
            "name": "app",
            "version": "0.1.0",
            "dependencies": [p.name for p in pkgs],
            "overrides": [{"name": p.name, "version": p.version} for p in pkgs],
            "builtin-baseline": "4b308f5ccd45aed57f2977257bca304dfef43c99",
        }
        private = [p.name for p in pkgs if p.source]
        if private:
            manifest["vcpkg-configuration"] = {
                "registries": [
                    {
                        "kind": "git",
                        "repository": next(p.source for p in pkgs if p.source),
                        "baseline": "0" * 40,
                        "packages": private,
                    }
                ]
            }
        (root / "vcpkg.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    @staticmethod
    def actions(root: Path, pkgs: list[Pkg]) -> None:
        """A workflow whose steps use each action: pinned to a commit with its release in a comment
        where the package has a hash, by release tag otherwise."""
        steps = "".join(
            f"      - uses: {p.name}@{p.integrity} # v{p.version}\n"
            if p.integrity
            else f"      - uses: {p.name}@v{p.version}\n"
            for p in pkgs
        )
        workflows = root / ".github" / "workflows"
        workflows.mkdir(parents=True)
        (workflows / "ci.yml").write_text(
            f"name: ci\non: push\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n{steps}",
            encoding="utf-8",
        )

    @staticmethod
    def ansible(root: Path, pkgs: list[Pkg]) -> None:
        """requirements.yml with each collection pinned; one with a source comes from a private
        Galaxy server (an Automation Hub)."""
        lines = ["collections:"]
        for p in pkgs:
            lines += [f"  - name: {json.dumps(p.name)}", f"    version: {json.dumps(p.version)}"]
            if p.source:
                lines.append(f"    source: {p.source}")
        (root / "requirements.yml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    @staticmethod
    def terraform(root: Path, pkgs: list[Pkg]) -> None:
        """versions.tf requiring each provider at its version, and the lock Terraform writes: the
        version, the constraint, and a zip hash; a provider with a source on a private registry."""
        required, locked = [], []
        for p in pkgs:
            address = f"{p.source}/{p.name}" if p.source else p.name
            local = p.name.rsplit("/", 1)[-1].replace(".", "-")
            required.append(
                f"    {json.dumps(local)} = {{\n      source  = {json.dumps(address)}\n      version = {json.dumps(p.version)}\n    }}"
            )
            hashes = f"  hashes = [\n    {json.dumps(p.integrity)},\n  ]\n" if p.integrity else ""
            host = "" if p.source else "registry.terraform.io/"
            locked.append(
                f"provider {json.dumps(host + address)} {{\n  version     = {json.dumps(p.version)}\n  constraints = {json.dumps(p.version)}\n{hashes}}}\n"
            )
        (root / "versions.tf").write_text(
            "terraform {\n  required_providers {\n" + "\n".join(required) + "\n  }\n}\n",
            encoding="utf-8",
        )
        (root / ".terraform.lock.hcl").write_text("\n".join(locked), encoding="utf-8")

    @staticmethod
    def helm(root: Path, pkgs: list[Pkg]) -> None:
        """Chart.yaml depending on each chart at its version from an HTTPS repository, and the
        Chart.lock `helm dependency update` writes."""
        repository = "https://charts.example.org/stable"
        deps = "".join(
            f"  - name: {json.dumps(p.name)}\n    version: {json.dumps(p.version)}\n    repository: {p.source or repository}\n"
            for p in pkgs
        )
        (root / "Chart.yaml").write_text(
            f"apiVersion: v2\nname: app\nversion: 1.0.0\ndependencies:\n{deps}", encoding="utf-8"
        )
        locked = "".join(
            f"- name: {json.dumps(p.name)}\n  repository: {p.source or repository}\n  version: {json.dumps(p.version)}\n"
            for p in pkgs
        )
        (root / "Chart.lock").write_text(
            f'dependencies:\n{locked}digest: sha256:{"a" * 64}\ngenerated: "2026-01-01T00:00:00Z"\n',
            encoding="utf-8",
        )

    @staticmethod
    def nix(root: Path, pkgs: list[Pkg]) -> None:
        """flake.nix taking each package as a GitHub input, and the flake.lock `nix flake lock`
        writes: each node locked at a revision (the profile's version, for matching) with its NAR
        hash."""
        inputs = "".join(
            f'    {json.dumps(f"in{i}")}.url = "github:{p.name}";\n' for i, p in enumerate(pkgs)
        )
        (root / "flake.nix").write_text(
            f"{{\n  inputs = {{\n{inputs}  }};\n  outputs = {{ self, ... }}: {{ }};\n}}\n",
            encoding="utf-8",
        )
        nodes: dict[str, object] = {
            "root": {"inputs": {f"in{i}": f"in{i}" for i in range(len(pkgs))}}
        }
        for i, p in enumerate(pkgs):
            owner, _, repo = p.name.partition("/")
            locked: dict[str, object] = {
                "lastModified": 1700000000,
                "owner": owner,
                "repo": repo,
                "rev": p.version,
                "type": "github",
            }
            if p.integrity:
                locked["narHash"] = p.integrity
            nodes[f"in{i}"] = {
                "locked": locked,
                "original": {"owner": owner, "repo": repo, "type": "github"},
            }
        (root / "flake.lock").write_text(
            json.dumps({"nodes": nodes, "root": "root", "version": 7}, indent=2), encoding="utf-8"
        )

    @staticmethod
    def bazel(root: Path, pkgs: list[Pkg]) -> None:
        """MODULE.bazel depending on each module, and the Bazel 7.2+ lock: the registry's
        source.json for each selected version, with the SHA-256 recorded."""
        deps = "".join(
            f"bazel_dep(name = {json.dumps(p.name)}, version = {json.dumps(p.version)})\n"
            for p in pkgs
        )
        (root / "MODULE.bazel").write_text(
            f'module(name = "app", version = "0.1.0")\n\n{deps}', encoding="utf-8"
        )
        hashes: dict[str, str] = {}
        for p in pkgs:
            registry = p.source or "https://bcr.bazel.build"
            hashes[f"{registry}/modules/{p.name}/{p.version}/source.json"] = (
                p.integrity or ""
            ).removeprefix("sha256:")
        (root / "MODULE.bazel.lock").write_text(
            json.dumps(
                {
                    "lockFileVersion": 13,
                    "registryFileHashes": hashes,
                    "selectedYankedVersions": {},
                    "moduleExtensions": {},
                },
                indent=2,
            ),
            encoding="utf-8",
        )

    @staticmethod
    def homebrew(root: Path, pkgs: list[Pkg]) -> None:
        """A Brewfile and the Brewfile.lock.json `brew bundle` wrote: each formula's version and
        bottle checksum. A package with a source comes from a private tap at that URL."""
        private = next((p.source for p in pkgs if p.source), None)
        lines = [f'tap "acme/internal", {json.dumps(private)}\n'] if private else []
        lines += [
            f'brew "acme/internal/{p.name}"\n' if p.source else f"brew {json.dumps(p.name)}\n"
            for p in pkgs
        ]
        (root / "Brewfile").write_text("".join(lines), encoding="utf-8")
        brew: dict[str, object] = {}
        for p in pkgs:
            digest = (p.integrity or "").removeprefix("sha256:")
            bottle: object = False
            if p.integrity:
                root_url = p.source or "https://ghcr.io/v2/homebrew/core"
                bottle = {
                    "rebuild": 0,
                    "root_url": root_url,
                    "files": {
                        "arm64_sonoma": {
                            "cellar": ":any",
                            "url": f"{root_url}/{p.name}/blobs/sha256:{digest}",
                            "sha256": digest,
                        }
                    },
                }
            brew[f"acme/internal/{p.name}" if p.source else p.name] = {
                "version": p.version,
                "bottle": bottle,
            }
        lock = {
            "entries": {"brew": brew},
            "system": {
                "macos": {"sonoma": {"HOMEBREW_VERSION": "4.3.24", "CLT": "15.3.0.0.1.1708646388"}}
            },
        }
        (root / "Brewfile.lock.json").write_text(json.dumps(lock, indent=2), encoding="utf-8")

    @staticmethod
    def image(root: Path, pkgs: list[Pkg]) -> None:
        """compose.yaml running each image as `name:tag`, with `@digest` where it has one; an image
        from a private registry is named with that registry's host."""
        lines = ["services:"]
        for index, p in enumerate(pkgs):
            host = (p.source or "").removeprefix("https://").rstrip("/")
            reference = f"{host + '/' if host else ''}{p.name}:{p.version}{'@' + p.integrity if p.integrity else ''}"
            lines.append(f"  service-{index}:\n    image: {json.dumps(reference)}")
        (root / "compose.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


class Hashes:
    @staticmethod
    def sri(n: int) -> str:
        return "sha512-" + chr(65 + n % 26) * 86 + "=="

    @staticmethod
    def sha256_colon(n: int) -> str:
        return "sha256:" + format(n, "x").rjust(64, "a")

    @staticmethod
    def hex64(n: int) -> str:
        return format(n, "x").rjust(64, "b")

    @staticmethod
    def sha512_hex(n: int) -> str:
        """A SHA-512 in hex, prefixed: what opam-repository and dune's lock record."""
        return "sha512:" + format(n, "x").rjust(128, "c")

    @staticmethod
    def conan_revision(n: int) -> str:
        """A Conan recipe revision: the MD5 of the recipe's manifest."""
        return "md5:" + format(n, "x").rjust(32, "d")

    @staticmethod
    def terraform_zip(n: int) -> str:
        """A provider zip's SHA-256, as a Terraform lock writes it."""
        return "zh:" + format(n, "x").rjust(64, "e")

    @staticmethod
    def nar(n: int) -> str:
        """A NAR hash in SRI form, as flake.lock writes it."""
        import base64

        return "sha256-" + base64.b64encode(n.to_bytes(32, "big")).decode()

    @staticmethod
    def hex64_prefixed(n: int) -> str:
        """A SHA-256 in hex, prefixed as the lock records it."""
        return "sha256:" + Hashes.hex64(n)

    @staticmethod
    def git_tree(n: int) -> str:
        """A Julia git-tree-sha1, in the form the General registry's digests are compared in."""
        return f"git-tree-sha1:{Hashes.hex40(n)}"

    @staticmethod
    def hex32(n: int) -> str:
        """An MD5, as renv's `Hash` records one."""
        return format(n, "x").rjust(32, "e")

    @staticmethod
    def hex40(n: int) -> str:
        """A SHA-1, as Composer's `dist.shasum` records one."""
        return format(n, "x").rjust(40, "c")

    @staticmethod
    def base64_sha512(n: int) -> str:
        """NuGet's `contentHash`: a bare base64 SHA-512."""
        return chr(65 + n % 26) * 86 + "=="

    @staticmethod
    def go(n: int) -> str:
        return "h1:" + chr(65 + n % 26) * 43 + "="


PROFILES: tuple[EcosystemProfile, ...] = (
    EcosystemProfile(
        id="npm",
        names=("left-pad", "is-number", "ms"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.npm,
        hash_of=Hashes.sri,
        malformed_hash="sha512-not a digest at all",
        typosquat=("lodash", "lodahs", "lodash-es"),
        internal=("@acme-internal/", "@acme-internal/billing"),
        private_source="https://npm.acme.example.internal/@acme-internal/billing/-/billing-1.0.0.tgz",
        executable={
            "package.json": json.dumps(
                {"name": "x", "version": "1.0.0", "scripts": {"test": f"touch {MARKER}"}}
            )
        },
        records_licence=True,
    ),
    EcosystemProfile(
        id="pypi",
        names=("left-pad-py", "isnumber", "ms-py"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.pypi,
        hash_of=Hashes.sha256_colon,
        malformed_hash="sha256:not-a-digest",
        typosquat=("requests", "requsets", "requests-oauthlib"),
        internal=("acme-internal-", "acme-internal-billing"),
        private_source="https://pypi.acme.example.internal/simple",
        executable={
            "setup.py": f"import pathlib\npathlib.Path({MARKER!r}).write_text('x')\nfrom setuptools import setup\nsetup(name='x')\n"
        },
    ),
    EcosystemProfile(
        id="cargo",
        names=("leftpad", "isnumber", "msrs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.cargo,
        hash_of=Hashes.hex64,
        malformed_hash="not-a-checksum",
        typosquat=("serde", "sedre", "serde_json"),
        internal=("acme-internal-", "acme-internal-billing"),
        private_source="registry+https://cargo.acme.example.internal/index",
        executable={"build.rs": f'fn main() {{ std::fs::write("{MARKER}", "x").unwrap(); }}\n'},
    ),
    EcosystemProfile(
        id="gomod",
        names=(
            "github.com/example/leftpad",
            "github.com/example/isnumber",
            "github.com/example/ms",
        ),
        versions=("v1.0.0", "v1.3.0", "v2.0.0+incompatible"),
        write=Writers.gomod,
        hash_of=Hashes.go,
        malformed_hash="h1:notadigest",
        typosquat=(
            "github.com/sirupsen/logrus",
            "github.com/sirupsen/logruss",
            "github.com/sirupsen/logrus/hooks",
        ),
        internal=("github.com/acme-internal/", "github.com/acme-internal/billing"),
        executable={
            "main.go": f'package main\nimport "os"\nfunc init() {{ os.WriteFile("{MARKER}", nil, 0o600) }}\nfunc main() {{}}\n'
        },
    ),
    EcosystemProfile(
        id="maven",
        names=("com.example:leftpad", "com.example:isnumber", "com.example:ms"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.maven,
        hash_of=Hashes.hex64,
        malformed_hash="not-a-checksum",
        typosquat=(
            "com.google.guava:guava",
            "com.google.guava:guvaa",
            "com.google.guava:guava-testlib",
        ),
        internal=("com.acme.internal", "com.acme.internal:billing"),
        executable={
            "mvnw": f"#!/bin/sh\ntouch {MARKER}\n",
            ".mvn/jvm.config": f"-javaagent:{MARKER}.jar\n",
            ".mvn/extensions.xml": "<extensions><extension><groupId>x</groupId><artifactId>y</artifactId><version>1</version></extension></extensions>\n",
        },
    ),
    EcosystemProfile(
        id="gradle",
        names=("com.example:leftpad", "com.example:isnumber", "com.example:ms"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.gradle,
        hash_of=Hashes.hex64,
        malformed_hash="not-a-checksum",
        typosquat=(
            "com.google.guava:guava",
            "com.google.guava:guvaa",
            "com.google.guava:guava-testlib",
        ),
        internal=("com.acme.internal", "com.acme.internal:billing"),
        executable={
            "settings.gradle.kts": f'java.io.File("{MARKER}").writeText("settings evaluated")\nrootProject.name = "app"\n',
            "buildSrc/build.gradle.kts": f'java.io.File("{MARKER}").writeText("buildSrc evaluated")\n',
            "gradlew": f"#!/bin/sh\ntouch {MARKER}\n",
            "init.gradle": f'new File("{MARKER}").text = "init script evaluated"\n',
        },
    ),
    EcosystemProfile(
        id="nuget",
        names=("Example.LeftPad", "Example.IsNumber", "Example.Ms"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.nuget,
        hash_of=Hashes.base64_sha512,
        malformed_hash="not-a-content-hash",
        typosquat=("Newtonsoft.Json", "Newtonsoft.Jsno", "Newtonsoft.Json.Bson"),
        internal=("Acme.Internal.", "Acme.Internal.Billing"),
        executable={
            "Directory.Build.targets": (
                f'<Project><Target Name="Marker" BeforeTargets="Restore;Build"><Exec Command="touch {MARKER}" /></Target></Project>\n'
            ),
            "Directory.Build.props": f'<Project><PropertyGroup><Marker>$([System.IO.File]::WriteAllText("{MARKER}", "x"))</Marker></PropertyGroup></Project>\n',
        },
    ),
    EcosystemProfile(
        id="composer",
        names=("example/leftpad", "example/isnumber", "example/ms"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.composer,
        hash_of=Hashes.hex40,
        malformed_hash="not-a-sha1",
        typosquat=("guzzlehttp/guzzle", "guzzlehttp/guzzel", "guzzlehttp/guzzle-services"),
        internal=("acme-internal/", "acme-internal/billing"),
        private_source="https://repo.acme-internal.example.internal/dist/acme-internal/billing.zip",
        executable={
            "src/Plugin.php": f'<?php\nfile_put_contents("{MARKER}", "plugin activated");\n',
            "scripts/post-install.php": f'<?php\ntouch("{MARKER}");\n',
        },
        records_licence=True,
    ),
    EcosystemProfile(
        id="rubygems",
        names=("leftpad-rb", "isnumber-rb", "ms-rb"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.rubygems,
        hash_of=Hashes.hex64,
        malformed_hash="not-a-checksum",
        typosquat=("rails", "rials", "rails-html-sanitizer"),
        internal=("acme-internal-", "acme-internal-billing"),
        private_source="https://gems.acme-internal.example.internal/",
        executable={
            "Gemfile.local": f'File.write("{MARKER}", "gemfile evaluated")\n',
            "app.gemspec": f'File.write("{MARKER}", "gemspec evaluated")\nGem::Specification.new {{ |s| s.name = "app" }}\n',
            "ext/native/extconf.rb": f'File.write("{MARKER}", "extension built")\n',
            "Rakefile": f'File.write("{MARKER}", "rake ran")\n',
        },
    ),
    EcosystemProfile(
        id="hex",
        names=("leftpad_ex", "isnumber_ex", "ms_ex"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.hex,
        hash_of=Hashes.hex64,
        malformed_hash="not-a-checksum",
        typosquat=("phoenix", "phoneix", "phoenix_html"),
        internal=("acme_internal_", "acme_internal_billing"),
        private_source="acme",
        executable={
            "config/config.exs": f'File.write!("{MARKER}", "config evaluated")\n',
            "rebar.config": f'{{pre_hooks, [{{compile, "touch {MARKER}"}}]}}.\n',
            "c_src/Makefile": f"all:\n\ttouch {MARKER}\n",
        },
    ),
    EcosystemProfile(
        id="pub",
        names=("leftpad_dart", "isnumber_dart", "ms_dart"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.pub,
        hash_of=Hashes.hex64,
        malformed_hash="not-a-sha256",
        typosquat=("provider", "provdier", "provider_test"),
        internal=("acme_internal_", "acme_internal_billing"),
        private_source="https://pub.acme-internal.example.internal",
        executable={
            "hook/build.dart": f'import "dart:io";\nvoid main() {{ File("{MARKER}").writeAsStringSync("x"); }}\n',
            "bin/main.dart": f'import "dart:io";\nvoid main() {{ File("{MARKER}").writeAsStringSync("x"); }}\n',
        },
    ),
    EcosystemProfile(
        id="swift",
        names=("example/leftpad-swift", "example/isnumber-swift", "example/ms-swift"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.swift,
        typosquat=("alamofire/alamofire", "alamofire/alamofrie", "alamofire/alamofireimage"),
        internal=("acme-internal/", "acme-internal/billing"),
        executable={
            "Plugins/Generate/plugin.swift": f'import Foundation\nlet _ = FileManager.default.createFile(atPath: "{MARKER}", contents: nil)\n',
            "Sources/App/main.swift": f'import Foundation\nFileManager.default.createFile(atPath: "{MARKER}", contents: nil)\n',
        },
    ),
    EcosystemProfile(
        id="cocoapods",
        names=("LeftPadKit", "IsNumberKit", "MsKit"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.cocoapods,
        hash_of=Hashes.hex40,
        malformed_hash="not-a-sha1",
        typosquat=("Alamofire", "Alamofrie", "AlamofireImage"),
        internal=("AcmeInternal", "AcmeInternalBilling"),
        private_source="https://github.com/acme-internal/private-specs.git",
        executable={
            "Local.podspec": f'File.write("{MARKER}", "podspec evaluated")\nPod::Spec.new {{ |s| s.name = "Local"; s.prepare_command = "touch {MARKER}" }}\n',
            "Podfile.local": f'File.write("{MARKER}", "podfile evaluated")\n',
        },
    ),
    EcosystemProfile(
        id="conda",
        names=("leftpad-conda", "isnumber-conda", "ms-conda"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.conda,
        hash_of=Hashes.hex64,
        malformed_hash="not-a-sha256",
        typosquat=("numpy", "nmupy", "numpy-base"),
        internal=("acme-internal-", "acme-internal-billing"),
        private_source="https://conda.acme-internal.example.internal/acme",
        executable={
            "recipe/build.sh": f"#!/bin/sh\ntouch {MARKER}\n",
            "recipe/meta.yaml": f'package:\n  name: x\n  version: "1"\nbuild:\n  script: touch {MARKER}\n',
        },
    ),
    EcosystemProfile(
        id="cran",
        names=("leftpadR", "isnumberR", "msR"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.cran,
        hash_of=Hashes.hex32,
        malformed_hash="not-an-md5",
        typosquat=("ggplot2", "ggplto2", "ggplot2movies"),
        internal=("acmeInternal", "acmeInternalBilling"),
        private_source="https://cran.acme-internal.example.internal/src/contrib/acmeInternalBilling_1.3.0.tar.gz",
        registry_digests=False,
        executable={
            "R/zzz.R": f'.onLoad <- function(lib, pkg) file.create("{MARKER}")\n',
            "configure": f"#!/bin/sh\ntouch {MARKER}\n",
            ".Rprofile": f'file.create("{MARKER}")\n',
        },
    ),
    EcosystemProfile(
        id="hackage",
        names=("leftpad", "is-number", "msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.hackage,
        hash_of=Hashes.hex64,
        malformed_hash="not-a-sha256",
        typosquat=("aeson", "aesno", "aeson-pretty"),
        internal=("acme-internal", "acme-internal-billing"),
        private_source="https://hackage.acme-internal.example.internal/package/acme-internal-billing-1.3.0.tar.gz",
        executable={
            # A custom Setup.hs runs at build time, and Template Haskell splices at compile time.
            "Setup.hs": f'import System.Process\nmain = callCommand "touch {MARKER}"\n',
            "src/Splice.hs": f'{{-# LANGUAGE TemplateHaskell #-}}\nmodule Splice where\nimport Language.Haskell.TH.Syntax\n$(runIO (writeFile "{MARKER}" "") >> return [])\n',
        },
    ),
    EcosystemProfile(
        id="julia",
        names=("LeftPad", "IsNumber", "Msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.julia,
        hash_of=Hashes.git_tree,
        malformed_hash="not-a-tree-hash",
        typosquat=("Distributions", "Distributons", "DistributionsAD"),
        internal=("AcmeInternal", "AcmeInternalBilling"),
        private_source="https://git.acme-internal.example.internal/julia/AcmeInternalBilling.jl.git",
        executable={
            # Pkg runs deps/build.jl on add and build; a module's top level runs when precompiled.
            "deps/build.jl": f'touch("{MARKER}")\n',
            "src/App.jl": f'module App\ntouch("{MARKER}")\nend\n',
        },
    ),
    EcosystemProfile(
        id="opam",
        names=("leftpad", "isnumber", "msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.opam,
        hash_of=Hashes.sha512_hex,
        malformed_hash="sha512:not-a-digest",
        typosquat=("cohttp", "cohtpt", "cohttp-lwt"),
        internal=("acme-internal", "acme-internal-billing"),
        private_source="git+https://git.acme-internal.example.internal/ocaml/acme-internal-billing.git#0123456789abcdef0123456789abcdef01234567",
        executable={
            # opam runs a package's build commands; dune runs rules and ppx rewriters.
            "app.opam": f'opam-version: "2.0"\nbuild: [["sh" "-c" "touch {MARKER}"]]\n',
            "bin/dune": f'(rule (action (system "touch {MARKER}")))\n',
        },
    ),
    EcosystemProfile(
        id="conan",
        names=("leftpad", "isnumber", "msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.conan,
        hash_of=Hashes.conan_revision,
        malformed_hash="md5:not-a-revision",
        typosquat=("spdlog", "spdolg", "spdlog_setup"),
        internal=("acme-internal", "acme-internal-billing"),
        private_source="acme/stable",
        executable={
            # A recipe is Python Conan imports; its methods run during `conan install`.
            "conanfile.py": f'import os\nos.system("touch {MARKER}")\nfrom conan import ConanFile\nclass App(ConanFile):\n    def requirements(self):\n        os.system("touch {MARKER}")\n',
        },
    ),
    EcosystemProfile(
        id="actions",
        names=("acme/leftpad-action", "acme/is-number-action", "acme/msecs-action"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.actions,
        hash_of=Hashes.hex40,
        typosquat=("actions/checkout", "actions/chekcout", "actions/cache"),
        executable={
            # An action's JavaScript runs in the job; a workflow's `run:` runs on the runner.
            "action.yml": "name: x\nruns:\n  using: node20\n  main: index.js\n",
            "index.js": f'require("fs").writeFileSync("{MARKER}", "")\n',
            ".github/workflows/run.yml": f"on: push\njobs:\n  x:\n    runs-on: ubuntu-latest\n    steps:\n      - run: touch {MARKER}\n",
        },
    ),
    EcosystemProfile(
        id="ansible",
        names=("acme.leftpad", "acme.is_number", "acme.msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.ansible,
        typosquat=("community.general", "community.genearl", "community.mysql"),
        internal=("acmecorp.", "acmecorp.billing"),
        private_source="https://hub.acmecorp.example.internal/api/galaxy/content/published/",
        registry_digests=False,
        executable={
            # A play's tasks, a role's tasks, and a module: all run on hosts, never on the scanner.
            "site.yml": f"- hosts: all\n  tasks:\n    - ansible.builtin.shell: touch {MARKER}\n",
            "roles/x/tasks/main.yml": f"- ansible.builtin.command: touch {MARKER}\n",
            "library/acme_module.py": f'open("{MARKER}", "w").close()\n',
        },
    ),
    EcosystemProfile(
        id="terraform",
        names=("acme/leftpad", "acme/isnumber", "acme/msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.terraform,
        hash_of=Hashes.terraform_zip,
        malformed_hash="zh:not-a-zip-hash",
        typosquat=("hashicorp/kubernetes", "hashicorp/kubernetse", "hashicorp/helm"),
        internal=("acmecorp/", "acmecorp/billing"),
        private_source="app.terraform.io",
        executable={
            # local-exec and the external data source run commands at plan or apply, never here.
            "main.tf": f'resource "null_resource" "x" {{\n  provisioner "local-exec" {{\n    command = "touch {MARKER}"\n  }}\n}}\ndata "external" "y" {{\n  program = ["sh", "-c", "touch {MARKER}"]\n}}\n',
        },
    ),
    EcosystemProfile(
        id="helm",
        names=("leftpad", "isnumber", "msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.helm,
        typosquat=("postgresql", "postgersql", "postgresql-ha"),
        executable={
            # A hook is a Kubernetes Job the cluster runs at install; the scanner never does.
            "templates/hook.yaml": f'apiVersion: batch/v1\nkind: Job\nmetadata:\n  annotations:\n    "helm.sh/hook": pre-install\nspec:\n  template:\n    spec:\n      containers:\n        - name: x\n          image: busybox\n          command: ["touch", "{MARKER}"]\n',
        },
    ),
    EcosystemProfile(
        id="nix",
        names=("acme/leftpad", "acme/isnumber", "acme/msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.nix,
        hash_of=Hashes.nar,
        malformed_hash="sha256-not-a-nar-hash",
        typosquat=("numtide/flake-utils", "numtide/flake-utlis", "numtide/flake-utils-plus"),
        registry_digests=False,
        executable={
            # Evaluating any of these would run a command; nothing here evaluates Nix.
            "default.nix": f'builtins.exec [ "touch" "{MARKER}" ]\n',
            "shell.nix": f'(import <nixpkgs> {{}}).runCommand "x" {{}} "touch {MARKER}"\n',
        },
    ),
    EcosystemProfile(
        id="image",
        names=("libfoo", "toolbox", "webkit"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.image,
        hash_of=Hashes.hex64_prefixed,
        malformed_hash="sha256:not-a-digest",
        internal=("acme/", "acme/billing"),
        private_source="https://registry.acme-internal.example.internal",
        executable={
            # Build instructions Docker runs, never this scanner.
            "Dockerfile": f"FROM alpine:3.20\nRUN touch {MARKER}\nONBUILD RUN touch {MARKER}\n",
        },
    ),
    EcosystemProfile(
        id="homebrew",
        names=("libyaml", "pcre2", "gmp"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.homebrew,
        hash_of=Hashes.hex64_prefixed,
        malformed_hash="sha256:not-a-digest",
        typosquat=("ripgrep", "ripgerp", "ripgrep-all"),
        internal=("acme-", "acme-billing"),
        private_source="https://git.acme-internal.example.internal/homebrew/internal.git",
        executable={
            # Ruby `brew` evaluates; nothing here does.
            "Brewfile": f'system "touch", "{MARKER}"\nbrew "jq"\n',
            "Formula/acme-cli.rb": f'class AcmeCli < Formula\n  url "https://example.invalid/acme-cli-1.0.tar.gz"\n  system "touch", "{MARKER}"\n  def install\n    system "touch", "{MARKER}"\n  end\nend\n',
        },
    ),
    EcosystemProfile(
        id="bazel",
        names=("leftpad", "is_number", "msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.bazel,
        hash_of=Hashes.hex64_prefixed,
        malformed_hash="sha256:not-a-digest",
        typosquat=("rules_python", "rules_pytohn", "rules_python_gazelle_plugin"),
        internal=("acme_", "acme_billing"),
        private_source="https://bazel-registry.acme-internal.example.internal",
        executable={
            # Starlark Bazel evaluates while loading the workspace, never here.
            "BUILD.bazel": f'genrule(name = "x", outs = ["x"], cmd = "touch {MARKER}")\n',
            "defs.bzl": f'def _impl(ctx):\n    ctx.execute(["touch", "{MARKER}"])\n',
        },
    ),
    EcosystemProfile(
        id="vcpkg",
        names=("leftpad", "isnumber", "msecs"),
        versions=("1.0.0", "1.3.0", "2.0.0"),
        write=Writers.vcpkg,
        typosquat=("protobuf", "protbouf", "protobuf-c"),
        internal=("acme-internal", "acme-internal-billing"),
        private_source="https://git.acme-internal.example.internal/vcpkg-registry.git",
        executable={
            # vcpkg runs a port's portfile.cmake to fetch and build it.
            "ports/leftpad/portfile.cmake": f'execute_process(COMMAND touch "{MARKER}")\n',
            "ports/leftpad/vcpkg.json": '{"name": "leftpad", "version": "1.3.0"}\n',
        },
    ),
)


class Profiles:
    @staticmethod
    def get(ecosystem: str) -> EcosystemProfile:
        return next(p for p in PROFILES if p.id == ecosystem)

    @staticmethod
    def ids() -> list[str]:
        return [p.id for p in PROFILES]

    @staticmethod
    def of(profiles: list[EcosystemProfile]) -> list[str]:
        """The ids of these profiles, for parametrize ids and `PROVES`."""
        return [p.id for p in profiles]


__all__ = ["MARKER", "PROFILES", "EcosystemProfile", "Hashes", "Pkg", "Profiles", "Writers"]
