source "https://rubygems.org"

# A helper method, as dual-boot Gemfiles define one: `def ... end` is a block like `do ... end`.
def next?
  File.basename(__FILE__) == "Gemfile.next"
end

gem "rack", "~> 3.0"

if next?
  gem "puma", "~> 6.4"
end

if ENV["WITH_PRY"] then gem "pry" end
