module(name = "modular", version = "2.0.0")

bazel_dep(name = "rules_jvm_external", version = "6.3")
bazel_dep(name = "protobuf", version = "27.0")
bazel_dep(name = "shared")
bazel_dep(name = "rules_go")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "com.google.guava:guava:33.3.1-jre",
        "org.slf4j:slf4j-api:" + "2.0.16",
    ],
    repositories = ["https://repo1.maven.org/maven2"],
)
use_repo(maven, "maven")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.23.1")

# Two versions of protobuf side by side in one graph.
multiple_version_override(
    module_name = "protobuf",
    versions = ["21.7", "27.0"],
)

local_path_override(
    module_name = "shared",
    path = "../shared",
)
