cabal-version: 2.4
name:          core
version:       1.0.0
license:       BSD-3-Clause
build-type:    Custom

custom-setup
  setup-depends:
      base >=4.18
    , Cabal >=3.10 && <3.12

flag fast
  description: Optimised build
  default:     False

library
  exposed-modules: Core
  build-depends:
      base        >=4.18 && <5
    , text        >=2.0
    , acme-billing ^>=0.4
    , zlib
  pkgconfig-depends: zlib >=1.2
  if impl(ghc >= 9.8)
    build-depends: ghc-compat >=0.1
  elif impl(ghc >= 9.6)
    build-depends: ghc-compat-legacy
  default-language: GHC2021
