#!/usr/bin/env python3
"""Write the hash pin the GitHub Action installs from.

The Action runs `pip install cordon-scanner==<version>`. The version is
validated against a strict pattern, which stops argument injection through
`CORDON_VERSION`, but it still trusts the index to serve the artefact that
version names. A compromised index, or a compromised release account, replaces
the security scanner with anything it likes, in every workflow that uses the
Action, and no pin on the Action's own commit SHA detects it: the SHA covers
`action.yml`, not what pip downloads.

`--require-hashes` closes that, and this script produces the file it reads.

There is no chicken-and-egg here, though it looks like one. Two sources are
supported and each is correct at a different moment:

`--from-dist` hashes artefacts already built, before they are uploaded. Use it
when the release publishes exactly the files it hashed, which makes the pin
right by construction and depends on no build being reproducible.

`--from-pypi` reads the digests the index reports for a version already
published. Use it to pin a release that went out without one, or to confirm
that what the index now serves is what was uploaded.

Both write the same file. Run with `--check` in CI to fail when the committed
pin no longer matches the version being released.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PIN = ROOT / "action" / "requirements.txt"
DISTRIBUTION = "cordon-scanner"

HEADER = """\
# Generated by scripts/pin_action_requirements.py. Do not edit by hand.
#
# The GitHub Action installs from this file with --require-hashes, so pip
# refuses any artefact whose digest is not listed here. Regenerate it as part of
# cutting a release, in the same commit that the release tag points at.
#
# Both the wheel and the sdist are listed because pip requires a hash for every
# file it might choose, and which one it picks depends on the runner.
"""


def from_dist(directory: Path, version: str) -> list[str]:
    """Digests of locally built artefacts, before they are uploaded."""
    prefix = DISTRIBUTION.replace("-", "_")
    files = sorted(
        path
        for path in directory.iterdir()
        if path.name.startswith(f"{prefix}-{version}") and path.suffix in {".whl", ".gz"}
    )
    if not files:
        raise SystemExit(f"no {DISTRIBUTION} {version} artefacts in {directory}")
    return [hashlib.sha256(path.read_bytes()).hexdigest() for path in files]


def from_pypi(version: str) -> list[str]:
    """Digests the index reports for a published version."""
    url = f"https://pypi.org/pypi/{DISTRIBUTION}/{version}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = json.load(response)
    digests = sorted(entry["digests"]["sha256"] for entry in payload["urls"])
    if not digests:
        raise SystemExit(f"{DISTRIBUTION} {version} has no files on PyPI")
    return digests


def render(version: str, digests: list[str]) -> str:
    lines = [HEADER, f"{DISTRIBUTION}=={version} \\"]
    lines.extend(f"    --hash=sha256:{digest} \\" for digest in digests[:-1])
    lines.append(f"    --hash=sha256:{digests[-1]}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--from-dist", type=Path, metavar="DIR")
    source.add_argument("--from-pypi", action="store_true")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed pin differs, instead of writing it",
    )
    args = parser.parse_args()

    digests = from_pypi(args.version) if args.from_pypi else from_dist(args.from_dist, args.version)
    content = render(args.version, digests)

    if args.check:
        current = PIN.read_text(encoding="utf-8") if PIN.exists() else ""
        if current != content:
            print(f"{PIN} is out of date; regenerate it", file=sys.stderr)
            return 1
        print(f"{PIN} matches {DISTRIBUTION} {args.version}")
        return 0

    PIN.parent.mkdir(parents=True, exist_ok=True)
    PIN.write_text(content, encoding="utf-8")
    print(f"wrote {PIN} for {DISTRIBUTION} {args.version} ({len(digests)} artefact(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
