"""Generated package-name allowlists, one file per ecosystem.

A package rather than a bare directory so `[tool.setuptools.package-data]` can
name it, which is what gets the `.txt` files into the wheel. Without that a
pip install falls back to the curated sets in `intel/real.py` -- not a crash, and
that is what makes it dangerous: the scanner works, and reports typosquats against
real packages in every installed copy while passing every test in a source
checkout.

Nothing here is importable beyond this docstring. The files are read as text by
`intel/real.py`, never imported, because forty thousand names as Python literals
would be parsed at every start-up to answer questions about one ecosystem.

Generated by `scripts/refresh_package_intel.py`. Do not edit by hand: the next
refresh overwrites them, and a name that needs to survive a refresh belongs in
that script's `KEEP_DESPITE_SHAPE`, with a reason, where it is reviewable.
"""
