"""Whether a release says where it came from.

A published artefact and the repository it claims to be built from are joined
by nothing but assertion. Anybody who can push to a registry can publish
anything under a name, and the tarball carries no record of the commit, the
workflow or the machine that produced it. That gap is what build provenance
closes: a signed statement, generated by the CI run itself and verifiable
afterwards, saying which source at which revision produced these bytes.

The tooling for it is now ordinary. `npm publish --provenance` emits a sigstore
bundle, `actions/attest-build-provenance` does the same for any artefact, PyPI
accepts PEP 740 attestations, and each of them costs one line in a workflow
that already has the identity token it needs. What is not ordinary is using
them, which is the whole point of reporting it: a project that publishes
without provenance has no way to prove, after a compromise, which of its
releases were its own.

**What this reads.** A CI workflow that publishes to a package registry, and
whether anything in the same file requests provenance, attestation or a
signature. Both halves are matched in the file rather than in the job, because
a workflow file is the unit somebody edits and the unit a reviewer reads; a
publish step in one job and an attestation step in another is a project that
has the machinery, which is the question being asked.

**Why it is POLICY and not SUSPICIOUS.** Nothing here is evidence of an attack.
A project without provenance is the majority of projects, and saying so is a
statement about what a compromise would cost to investigate, not a claim that
one happened. It is reported at low severity, and a project that has decided
against it can disable the rule by id.

**Why this is not a check on dependencies.** Whether a *dependency* was
published with provenance is a question for its registry, not for anything in
this repository, and it is answered by the online detector. This one is about
what the scan target itself publishes, which is the half nobody else will
check.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from cordon_scanner.core.models import (
    Category,
    Confidence,
    Evidence,
    EvidenceKind,
    Explanation,
    Finding,
    Location,
    RedactionMode,
    Severity,
)
from cordon_scanner.core.scoring import ScoringContext
from cordon_scanner.core.walker import PathGlob
from cordon_scanner.detect.base import BaseDetector, DetectorRequirements, FileUnit, ScanContext
from cordon_scanner.detect.catalogue import DeclaredRule

if TYPE_CHECKING:
    from collections.abc import Iterable

    from cordon_scanner.detect.base import Unit

RELEASE_PATHS = (
    "**/.github/workflows/*.yml",
    "**/.github/workflows/*.yaml",
    "**/.gitlab-ci.yml",
    "**/.gitlab-ci.yaml",
)
"""Where a release is automated.

Deliberately narrower than the CI globs the configuration detector uses. A
Jenkinsfile or a Makefile may well publish, and neither has a provenance story
this could look for -- reporting their absence would be reporting that a
feature of GitHub Actions is missing from a tool that does not have it."""

MAX_BYTES = 512 << 10
"""Workflow files are small. Anything past this is generated, and scanning half
a megabyte of it to answer one question is not worth the time."""


PUBLISHES = re.compile(
    rb"""(?ix)
    (?:
        pypa/gh-action-pypi-publish       # PyPI, the official action
      | twine[ \t]{1,8}upload
      | npm[ \t]{1,8}publish
      | pnpm[ \t]{1,8}publish
      | yarn[ \t]{1,8}(?:npm[ \t]{1,8})?publish
      | cargo[ \t]{1,8}publish
      | gem[ \t]{1,8}push
      | dotnet[ \t]{1,8}nuget[ \t]{1,8}push
      | mvn[ \t\w-]{0,40}deploy
      | gradle[ \t\w-]{0,40}publish
      | goreleaser[ \t]{1,8}release
    )
    """
)
"""A step that puts an artefact somewhere other people install from.

Matched on the command rather than on a job name, because `release`, `deploy`
and `publish` are job names for plenty of workflows that ship nothing, and a
rule keyed on them would report the wrong files in both directions."""


ATTESTS = re.compile(
    rb"""(?ix)
    (?:
        actions/attest                    # attest-build-provenance, attest-sbom
      | slsa-framework/slsa-github-generator
      | sigstore/gh-action-sigstore-python
      | sigstore/cosign-installer
      | gh[ \t]{1,8}attestation
      | cosign[ \t]{1,8}(?:sign|attest)
      | --provenance                      # npm publish --provenance
      | provenance[ \t]{0,8}:[ \t]{0,8}true
      | attestations[ \t]{0,8}:[ \t]{0,8}write
      | \bsyft\b|\bskopeo\b
    )
    """
)
"""Anything that produces a verifiable statement about the build.

The list is generous on purpose. This rule is about whether a project has
thought about provenance at all, and a project signing with cosign has, even
though the artefact it signs is not the one this rule noticed being
published."""


class AttestationDetector(BaseDetector):
    """Reports a release pipeline that publishes without provenance."""

    id = "attestation"
    version = "0.1.0"
    categories = frozenset({Category.POLICY})
    requires = DetectorRequirements(content=True)

    def applicable(self, ctx: ScanContext) -> bool:
        return True

    @staticmethod
    def declared_rules() -> tuple[DeclaredRule, ...]:
        return (
            DeclaredRule(
                id="POLICY.RELEASE.NO_PROVENANCE.001",
                title="Release workflow publishes without build provenance",
                severity=Severity.LOW,
                confidence=Confidence.MEDIUM,
                category=Category.POLICY,
                detector=AttestationDetector.id,
                remediation=(
                    "Add provenance to the publish step: `npm publish "
                    "--provenance`, `actions/attest-build-provenance`, or PEP "
                    "740 attestations for PyPI. Each needs `id-token: write` "
                    "and one line. Without it there is no way to establish, "
                    "after a compromise, which releases were yours."
                ),
            ),
        )

    def inspect(self, unit: Unit, ctx: ScanContext) -> Iterable[Finding]:
        if not isinstance(unit, FileUnit):
            return ()

        content = unit.content
        if content.is_binary or len(content.raw) > MAX_BYTES:
            return ()
        if not any(PathGlob.matches(content.path, glob) for glob in RELEASE_PATHS):
            return ()

        published = PUBLISHES.search(content.raw)
        if published is None or ATTESTS.search(content.raw) is not None:
            return ()

        declared = self.declared_rules()[0]
        step = published.group(0).decode("utf-8", "replace").strip()
        detail = (
            f"{content.path} publishes with {step!r} and requests no build "
            f"provenance. The artefact it uploads carries no verifiable record "
            f"of the commit or the workflow that produced it, so after a "
            f"compromise there is no way to tell an authentic release from a "
            f"forged one."
        )
        return [
            Finding(
                rule_id=declared.id,
                category=declared.category,
                severity=declared.severity,
                confidence=declared.confidence,
                message=detail,
                location=Location(
                    path=content.path,
                    line=content.line_of(published.start()),
                    project=unit.project,
                ),
                evidence=Evidence(
                    kind=EvidenceKind.HASH,
                    match_hash=Evidence.hash_bytes(published.group(0)),
                    redaction=RedactionMode.HASH_ONLY,
                ),
                remediation=declared.remediation,
                explanation=Explanation(summary=detail, matched_rule=declared.id),
                risk=ctx.scorer.score(
                    declared.severity,
                    declared.confidence,
                    ScoringContext(in_install_hook=False, capabilities=frozenset()),
                ),
                detector=self.id,
            )
        ]


__all__ = ["ATTESTS", "PUBLISHES", "RELEASE_PATHS", "AttestationDetector"]
